version: "3.7"
services:

  back:
    build:
      context: ./back
    working_dir: /back
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./back:/back
      - ./gql-schema:/gql-schema
      - ./.env:/back/.env
    depends_on:
      - db
    command: sh -c "npm install && npm run migration:run && npm run seed:drop && npm run seed && npm run test && npm run test:e2e"

  db:
    platform: "linux/amd64"
    image:
      postgres:14.1
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev_sample
      POSTGRES_ROOT_PASSWORD: dev_sample
      POSTGRES_INITDB_ARGS: "--encoding=utf8 --locale=en_US.utf8"
      TZ: "Asia/Tokyo"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
