name: lint-ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-lint-back:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: back/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run fmt
  ci-lint-front:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: front/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run fmt
