name: tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  # Runs on Circle CI
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        env:
          ENV: ${{ secrets.ENV_TEST }}
        run: echo "$ENV" > .env
      - run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
  graphql-inspector:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@v3.1.1
        with:
          schema: main:gql-schema/schema.gql
          fail-on-breaking: false
